### PR TITLE
Introduce global_build_dir

### PR DESCRIPTION
**Pull request by dabrain34**
Allow to change the global build dir where cerbero
creates the build artifacts.

### CODE REVIEW

**Comment by ylatuya** [comment]
Like we discussed I don't see the point of this new variable in cerbero itself, since it's unused by cerbero and cerbero has already a mechanism for that, which is home_dir.

Instead, to pass external properties I would add a new property field called extra_properties, a dicctionary in which we add random key:values for custom use in extensions like fluendo-cerbero.

For example, in your cerbero.cbc you could then have:
extra_properties =  {'global_build_dir': '/path'}

**Comment by segfaultxavi** [comment]
I agree with ylatuya, Cerbero only needs to know about home_dir. If we use Cerbero as part of a greater buildsystem, that is our problem, not Cerbero's.
I am sorry I did not understand before these changes.

**Comment by dabrain34** [comment]
So ylatuya you'll advise to add this to cerbero/config.py and then use it in fluendo-cerbero right ?

**Comment by dabrain34** [comment]
This pull request needs https://github.com/fluendo/cerbero/pull/59

**Pull request merged**
