### PR TITLE
FFMPEG-513 Add support for Ubuntu Jammy

### PR DESCRIPTION
**Pull request by aslobodeniuk**

### CODE REVIEW

**Comment by rgonzalezfluendo** [comment]
I did similar work in https://github.com/fluendo/cerbero/pull/361 (nor merged because it breaks flusdk)

**Comment by rgonzalezfluendo** [comment]
Can you cherry-pick commit from upstream? 

like https://gitlab.freedesktop.org/gstreamer/cerbero/-/commit/82ffb5b18daee149a0f00aaded08499001add4c5

**Comment by aslobodeniuk** [comment]
> Could you mention what's the issue with compiling it with orc==0.4.30?

Added a description to the commit message

https://github.com/fluendo/cerbero/pull/366/commits/14560ffebb28074f778c887bbc96e44e85897072

**Comment by aslobodeniuk** [comment]
> I did similar work in #361 (nor merged because it breaks flusdk)

thanks, I've just cherry-picked 2 commits from it

**Comment by aslobodeniuk** [comment]
> Can you cherry-pick commits from upstream?
> 
> like
> 
> * https://gitlab.freedesktop.org/gstreamer/cerbero/-/commit/82ffb5b18daee149a0f00aaded08499001add4c5
> * https://gitlab.freedesktop.org/gstreamer/cerbero/-/commit/9e248ae3d88882f60e75898f00d5a34a5e60a135
> * [43932ba](https://github.com/fluendo/cerbero/commit/43932ba03e51d8bace1cfdbe378ed548d001ccc6)

I've cherry-picked 2 commits from your PR (changing m4 and detecting distro version).
Regarding the orc, commit from your PR has too much unrelated changes.

Commits from the community do not apply as is.

**Review by rgonzalezfluendo — APPROVED** [review]

**Pull request merged**
