### PR TITLE
Fix linux cross compilation: x86_64->x86

### PR DESCRIPTION
**Pull request by aslobodeniuk**
Remove toolchain prefix and use only the
gcc -m option to define the target architecture.

### CODE REVIEW

**Comment by dabrain34** [comment]
Can you review the title fo something like that
linux cross-compile across processors address space

**Comment by aslobodeniuk** [comment]
@dabrain34 
message is fixed, so as title of pull request.

**Comment by dabrain34** [comment]
Fix linux cross compilation: x86_64->x86

Remove toolchain prefix and use only the 
gcc -m option to define the target architecture.

**Comment by aslobodeniuk** [comment]
@dabrain34 done.

**Pull request merged**
